<a href="https://colab.research.google.com/github/xhdixhfl/kaggler/blob/main/numpy%2C_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# while을 이용한 평균구하기

In [4]:
total = 0
count = 0
num = input("enter a numbeer (enter key = quit)")

while num != "":
  try:
    x = float(num)
    count += 1
    total = total +x
  except ValueError:
    print('Not a  number!')
  num = input("enter a numbeer (enter key = quit)")
avg = total / count
print(f'average={avg}')
    

enter a numbeer (enter key = quit)50
enter a numbeer (enter key = quit) 
Not a  number!
enter a numbeer (enter key = quit)64
enter a numbeer (enter key = quit)
average=57.0


# 배열
- 다른 언어에서는 배열의 크기를 정해둬야하는 경우가 있지만 파이썬의 리스트의 경우는 임의의 데이터타입을 담을수 있는 가변적 연속열(Sequence)형이다. 즉, 동적배열(Dynamic Array)

In [7]:
def nums():
  X= [ ] 
  while True:
    num = input("enter a number(if you want quit, enter key)")
    while num != "":
      try:
        x = float(num)
        X.append(x)
      except ValueError:
        print('Not a number')
      num =  input("enter a number(if you want quit, enter key)")
    if len(X) > 1:
      return X


X= nums()
print('X = ', X)

enter a number(if you want quit, enter key)50
enter a number(if you want quit, enter key)1
enter a number(if you want quit, enter key)64
enter a number(if you want quit, enter key)32
enter a number(if you want quit, enter key)05 
enter a number(if you want quit, enter key)
X =  [50.0, 1.0, 64.0, 32.0, 5.0]


In [8]:
import array as arr

mls = [1,2,3]
print(type(mls))

mls.append('4') # 끝자리에 추가
print(mls)

mls.insert(1,5) # 1자리에 5 삽입
print(mls)

marr = arr.array('i', [1,2,3])
print(type(marr))
print(marr)

marr.insert(1,5)
print(marr)

<class 'list'>
[1, 2, 3, '4']
[1, 5, 2, 3, '4']
<class 'array.array'>
array('i', [1, 2, 3])
array('i', [1, 5, 2, 3])


In [9]:
# list를 활용한 시그마 표현
tot = 0.0
for i in range(len(X)):
  tot = tot+X[i]
mean = tot / len(X)

print('sum of X', tot)

sum of X 152.0


In [10]:
# median 구현 코드
def median(nums):
  nums.sort() # 정렬 먼저
  size = len(nums)
  p = size // 2
  if size % 2 ==0:
    pr = p
    pl = p-1
    mid = float((nums[pl]+nums[pr])/2)
  else:
    mid = nums[p]
  return mid
print("X:", X)
median(X)

X: [50.0, 1.0, 64.0, 32.0, 5.0]


32.0

In [11]:
# 평균
def means(nums):
  tot = 0.0
  for i in range(len(nums)):
    tot = tot + nums[i]
  return tot / len(nums)

avg = means(X)

# 표준편차
def std_dev(nums, avg):
  texp =0.0
  for i in range(len(nums)):
    texp = texp + (nums[i]-avg)**2
  return (texp/(len(nums)-1)) ** 0.5

std_dev(X,avg)

27.50090907588329

In [12]:
# 전체 
def main():
  X= nums()
  med = median(X)
  avg = means(X)
  std = std_dev(X,avg)
  print(f"당신이 입력한 숫자{X}의")
  print("중앙값은 {}, 평균은 {}, 표준편자는 {}입니다.".format(med, avg, std))

if __name__ == '__main__':
  main()

enter a number(if you want quit, enter key)45
enter a number(if you want quit, enter key)18
enter a number(if you want quit, enter key)20
enter a number(if you want quit, enter key)156
enter a number(if you want quit, enter key)
당신이 입력한 숫자[18.0, 20.0, 45.0, 156.0]의
중앙값은 32.5, 평균은 59.75, 표준편자는 65.3318452211477입니다.


# numpy
## ndarray 만들기

In [14]:
import numpy as np

A = np.arange(5)
B = np.array([0,1,2,3,4])

C = np.array([0,1,2,3,'4'])

D = np.ndarray((5,), np.int64, np.array([0,1,2,3,4]))

print(A, type(A))
print("-"*20)
print(B, type(B))
print("-"*20)
print(C, type(C))
print("-"*20)
print(D, type(D))
print("-"*20)

[0 1 2 3 4] <class 'numpy.ndarray'>
--------------------
[0 1 2 3 4] <class 'numpy.ndarray'>
--------------------
['0' '1' '2' '3' '4'] <class 'numpy.ndarray'>
--------------------
[0 1 2 3 4] <class 'numpy.ndarray'>
--------------------


## 크기(size, shape, ndim)

In [15]:
A = np.arange(10).reshape(2, 5) # 1차원 길이 10 행렬을 2X5 2차원 행렬로

print('shape : ', A.shape)
print('dim : ', A.ndim)
print('size : ', A.size)

shape :  (2, 5)
dim :  2
size :  10


In [16]:
A = np.arange(6).reshape(2,3)
print(A, A.dtype, type(A))
print('-'*20)

B = np.array([0,1,2,3,4,5])
print(B, B.dtype, type(B))
print('-'*20)

C = np.array([0,1,2,3,'4',5])
print(C, C.dtype, type(C))
print('-'*20)

D = np.array([0,1,2,3,[4,5], 6])
print(D, D.dtype, type(D))
print('-'*20)    # 경고는 뜨지만, 리스트보다 큰 객체로 인식해줌

[[0 1 2]
 [3 4 5]] int64 <class 'numpy.ndarray'>
--------------------
[0 1 2 3 4 5] int64 <class 'numpy.ndarray'>
--------------------
['0' '1' '2' '3' '4' '5'] <U21 <class 'numpy.ndarray'>
--------------------
[0 1 2 3 list([4, 5]) 6] object <class 'numpy.ndarray'>
--------------------


<ipython-input-16-7c2a86ae63b0>:13: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  D = np.array([0,1,2,3,[4,5], 6])


In [17]:
C = np.array([0,1,2,3,'4',5])
print(C[0])
print(type(C[0]))
print(C[4])
print(type(C[4]))
print("------------------------------")

D = np.array([0,1,2,3,[4,5],6])
print(D[0])
print(type(D[0]))
print(D[4])
print(type(D[4]))

0
<class 'numpy.str_'>
4
<class 'numpy.str_'>
------------------------------
0
<class 'int'>
[4, 5]
<class 'list'>


<ipython-input-17-0979e0fcd31a>:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  D = np.array([0,1,2,3,[4,5],6])


- C[0]해당하는 숫자 0은 행렬 안에 문자열 '0'으로 들어가 있었음.
- 그러나 D[0]에 해당하는 숫자 0은 여전히 행렬 안에 정수 0으로 들어가 있음
- NumPy는 어떤 경우라도 Array 답게 연산속도를 최적화하도록 원소들을 관리하지만, 필요에 따라 가장 효율적인 방법으로 type을 변화시켜 관리함

## 특수행렬

In [20]:
# 단위 행렬
print(np.eye(3))
print('-'* 20)
# 0행렬
print(np.zeros([2,3]))
print('-'* 20)
# 1행렬
print(np.ones([3,3]))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------
[[0. 0. 0.]
 [0. 0. 0.]]
--------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## broadcast

In [27]:
A = np.arange(9).reshape(3,3)
print('raw ', A)

print('A에 2를 상수배 \n ' , A*2)

print('A + 2 \n ', A + 2)

B = np.array([1,2,3]) # 1X3 배열
print('A+B \n', A+B)
print('A*B \n', A*B)

raw  [[0 1 2]
 [3 4 5]
 [6 7 8]]
A에 2를 상수배 
  [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
A + 2 
  [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
A+B 
 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]
A*B 
 [[ 0  2  6]
 [ 3  8 15]
 [ 6 14 24]]


In [28]:
# 슬라이싱
# 이 슬라이싱의 결과는 
print(A[:,2:])
print("--------------")
print(A[:,1:])
print("--------------")
print(A[:,:])
print("--------------")
# 이 슬라이싱의 결과와 동일합니다.
print(A[:,-1:])
print("--------------")
print(A[:,-2:])
print("--------------")
print(A[:,-3:])

[[2]
 [5]
 [8]]
--------------
[[1 2]
 [4 5]
 [7 8]]
--------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------
[[2]
 [5]
 [8]]
--------------
[[1 2]
 [4 5]
 [7 8]]
--------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
A[:,-1]

array([2, 5, 8])

## Random

In [30]:
# 의사 난수를 생성
print(np.random.random())   # 0에서 1사이의 실수형 난수 하나를 생성

print(np.random.randint(0,10))   # 0~9 사이 1개 정수형 난수 하나를 생성

print(np.random.choice([0,1,2,3,4,5,6,7,8,9]))   # 리스트에 주어진 값 중 하나를 랜덤

0.5821364547464386
4
3


In [31]:
# 무작위로 섞인 배열 생성
# 아래 2가지 기능면에서 동일. 

print(np.random.permutation(10))   
print(np.random.permutation([0,1,2,3,4,5,6,7,8,9]))

[5 9 0 6 7 1 3 8 2 4]
[2 6 0 1 3 9 4 5 7 8]


In [32]:
# 아래 기능들은 어떤 분포를 따르는 변수를 임의로 표본추출

# 정규분포
print(np.random.normal(loc=0, scale=1, size=5))    # 평균(loc), 표준편차(scale), 추출개수(size)를 조절가능

#  균등분포
print(np.random.uniform(low=-1, high=1, size=5))  # 최소(low), 최대(high), 추출개수(size)를 조절가능

[ 0.57972657  0.25470068 -0.4907568  -1.44662862  0.26058853]
[-0.26916093  0.15672781 -0.83384785 -0.6229987   0.78671151]


## 전치행렬

In [33]:
A = np.arange(24).reshape(2,3,4)
print("A:", A)               # A는 (2,3,4)의 shape
print("A의 전치행렬:", A.T)            
print("A의 전치행렬의 shape:", A.T.shape) # A의 전치행렬은 (4,3,2)의 shape

A: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
A의 전치행렬: [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
A의 전치행렬의 shape: (4, 3, 2)


In [34]:
# np.transpose는 행렬의 축을 어떻게 변환해 줄지 임의로 지정해 줄 수 있는 일반적인 행렬 전치 함수. 
# np.transpose(A, (2,1,0)) 은 A.T와 같음

B = np.transpose(A, (2,0,1))
print("A:", A)             # A는 (2,3,4)의 shape를 가진 행렬
print("B:", B)             # B는 A의 3, 1, 2번째 축을 자신의 1, 2, 3번째 축으로 가진 행렬.
print("B.shape:", B.shape)  # B는 (4,2,3)의 shape를 가진 행렬

A: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
B: [[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]
B.shape: (4, 2, 3)


In [35]:
import numpy as np

def numbers():
    X = []
    number = input("Enter a number (<Enter key> to quit)") 
    # 하지만 2개 이상의 숫자를 받아야 한다는 제약조건을 제외함
    while number != "":
        try:
            x = float(number)
            X.append(x)
        except ValueError:
            print('>>> NOT a number! Ignored..')
        number = input("Enter a number (<Enter key> to quit)")
    return X

def main():
    nums = numbers()    
    num = np.array(nums)   # 리스트를 Numpy ndarray로 변환
    print("합", num.sum())
    print("평균값",num.mean())
    print("표준편차",num.std())
    print("중앙값",np.median(num))  

main()

Enter a number (<Enter key> to quit)51
Enter a number (<Enter key> to quit)64
Enter a number (<Enter key> to quit)8
Enter a number (<Enter key> to quit)02
Enter a number (<Enter key> to quit)
합 125.0
평균값 31.25
표준편차 26.733639856929322
중앙값 29.5
